# Documentation: https://roots.io/trellis/docs/vault/
vault_mysql_root_password: stagingpw

# Documentation: https://roots.io/trellis/docs/security/
vault_users:
  - name: "{{ admin_user }}"
    password: celis-produce-admin
    salt: "generateme"

# Variables to accompany `group_vars/staging/wordpress_sites.yml`
# Note: the site name (`example.com`) must match up with the site name in the above file.
vault_wordpress_sites:
  celis-produce.com:
    env:
      db_password: celis-produce_dbpassword
      # Generate your keys here: https://roots.io/salts.html
      auth_key: "#0;kjtmiR;(ULu,SIT<9Gvafy}!c<gVZygkmS_AN3&Q8F%!/PPbs7F<,}X!C[1<#"
      secure_auth_key: "obc3c{[<.;M8B)#%o[EnpVii}1Q!C<O}!=@q]_Us6d<TM^l9X[(Qo*q<,fyVx.sC"
      logged_in_key: "k#CaRzoVn|e/BinJkqwi5+wb^Qe#J8,xC@<tpsMAN@nb;X1%vR@*)[g(pKRUFkas"
      nonce_key: "%wuac^4bX8*s0=Mo`q,(ix@z#FOr}C&Lh,5{{fAfE5}yueCVNs3?2Q&cgkF}i&n["
      auth_salt: "l`6YCI`Kqk+}VT)52(NXpW99emoWzBH!<cOxLOHN7BS(*QjG(.(S?jW_<axVw`u}"
      secure_auth_salt: "3[&B*d#^1tZX`;c-aP(@I,6HMk>v_wBXbVCGuI:PrF7]i:^Vi<.$x$W6P!hTU^8@"
      logged_in_salt: "U^5iHq%jtM_YBQTs,F0Cmz8nx#aop>EPj8uCVM]UCHnw[qMi@3Prvk=-W[SILJn7"
      nonce_salt: "J-a5Q|^y/#t.+k8p2GAE}[el=V;oXi|K!^G:z![$J+gVBF7JtGw4MeQL.2q;zGH}"
